"use client";
import {useEffect,useState,useRef} from 'react';
import {ArrowUpRight,ArrowRight,Phone,Leaf,Scissors,Trees,Sprout,Shovel,Recycle,MapPin,ImageIcon,Menu,X,Star,Check,Quote} from 'lucide-react';
import {site} from './site-config';
import {demoStartedAt} from './demo-start';
import {BotanicalAccent} from './botanical-accent';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const serviceIcons=[Sprout,Leaf,Scissors,Trees,Shovel,Recycle];
const services=site.services.map((service,i)=>({...service,icon:serviceIcons[i%serviceIcons.length]}));
const nav=[['Services','services'],['Our Work','work'],['Reviews','reviews'],['Areas We Cover','areas'],['Contact','quote']];
function Brand(){return <a href="#home" className="brand" aria-label={site.name+' home'}>{site.logo?<img className="brand-logo" src={site.logo} alt={site.name}/>:<span className="brand-icon"><Leaf size={27}/></span>}<span>{site.brandLine}<small>{site.brandSubline}</small></span></a>}
function HeroVideo(){const video=useRef<HTMLVideoElement>(null);const [playing,setPlaying]=useState(true);const [enabled,setEnabled]=useState(false);useEffect(()=>{const query=window.matchMedia('(prefers-reduced-motion: no-preference)');const change=()=>setEnabled(query.matches);change();query.addEventListener('change',change);return()=>query.removeEventListener('change',change)},[]);return <><div className="hero-motion" style={{animationPlayState:playing?"running":"paused"}}><img className="hero-background" src={site.heroPoster} alt="Illustrative landscaped garden with a lawn and circular stone patio" fetchPriority="high"/>{enabled&&<video className="hero-background" ref={video} autoPlay muted loop playsInline preload="metadata" poster={site.heroPoster} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)}><source src={site.heroVideo} type="video/mp4"/></video>}</div>{enabled&&<button className="video-toggle" aria-label={playing?'Pause background video':'Play background video'} onClick={()=>{if(video.current){if(video.current.paused)void video.current.play();else video.current.pause()}}}>{playing?'Pause video':'Play video'}</button>}</>}
const SEVEN_DAYS = 7 * 24 * 60 * 60 * 1000;

const previewExpiresAt =
  String(demoStartedAt) === 'AUTO'
    ? Date.now() + SEVEN_DAYS
    : new Date(demoStartedAt).getTime() + SEVEN_DAYS;
function PreviewCountdown(){const [remaining,setRemaining]=useState<number|null>(null);useEffect(()=>{const update=()=>setRemaining(Math.max(0,previewExpiresAt-Date.now()));update();const timer=window.setInterval(update,1000);return()=>window.clearInterval(timer)},[]);if(remaining===0)return <div className="countdown-bar"><div className="countdown-inner"><strong>Free Website Preview</strong><span>This demo will remain live for 7 days.</span><b>This preview has expired.</b></div></div>;const totalSeconds=Math.floor((remaining??604800000)/1000);const days=Math.floor(totalSeconds/86400);const hours=Math.floor(totalSeconds%86400/3600);const minutes=Math.floor(totalSeconds%3600/60);const seconds=totalSeconds%60;return <div className="countdown-bar"><div className="countdown-inner"><strong>Free Website Preview</strong><span>This demo will remain live for 7 days.</span><b role="timer" aria-label={`${days} days ${hours} hours ${minutes} minutes ${seconds} seconds remaining`} suppressHydrationWarning>{days} Days {String(hours).padStart(2,'0')} Hours {String(minutes).padStart(2,'0')} Minutes {String(seconds).padStart(2,'0')} Seconds</b></div></div>}
export default function Home(){const [menu,setMenu]=useState(false);const [service,setService]=useState('');const [notice,setNotice]=useState('');const [gallery,setGallery]=useState<number|null>(null);
useEffect(()=>{
 const desktop=window.matchMedia('(min-width: 801px)');
 let cleanup=()=>{};
 const setup=()=>{
  cleanup();
  const targets:HTMLElement[]=[];
  const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){const group=entry.target as HTMLElement;group.classList.add('visible');group.querySelectorAll('.desktop-motion').forEach(el=>el.classList.add('visible'));observer.unobserve(group)}})},{threshold:0,rootMargin:'0px 0px -40px 0px'});
  if(desktop.matches){
   const groups=document.querySelectorAll<HTMLElement>('.section-heading, .service-grid, .editorial-project, .review-grid, .area-inner, .quote-support, .quote-copy, .quote-panel form, .stats, .work-bottom, .review-template-note, .footer-main');
   groups.forEach(group=>{
    let elements:HTMLElement[]=[];
    if(group.matches('.service-grid, .review-grid')) elements=Array.from(group.querySelectorAll<HTMLElement>(':scope > article'));
    else if(group.matches('.editorial-project')) elements=Array.from(group.querySelectorAll<HTMLElement>('.project-visual, .project-info > *'));
    else if(group.matches('.area-inner')) elements=Array.from(group.children) as HTMLElement[];
    else if(group.matches('.section-heading, .quote-copy')) elements=Array.from(group.querySelectorAll<HTMLElement>('h2, p, .call-card, .form-disclaimer')).filter(el=>!el.parentElement?.closest('.form-disclaimer'));
    else elements=[group];
    elements.forEach((el,i)=>{el.classList.add('desktop-motion');el.style.setProperty('--entrance-delay',`${i*(group.matches('.area-inner')?150:100)}ms`);targets.push(el)});
    observer.observe(group);
   });
  }else{
   document.querySelectorAll<HTMLElement>('.reveal, main section:not(#home) h2, main section:not(#home) h3, main section:not(#home) p, main section:not(#home) .button, .quote-panel form, .footer-main, .project-image').forEach(el=>{el.classList.add('reveal-ready');targets.push(el);observer.observe(el)});
  }
  cleanup=()=>{observer.disconnect();targets.forEach(el=>{el.classList.remove('desktop-motion','reveal-ready','visible');el.style.removeProperty('--entrance-delay')})};
 };
 setup();desktop.addEventListener('change',setup);return()=>{cleanup();desktop.removeEventListener('change',setup)};
},[]);
useEffect(()=>{
 const media=window.matchMedia('(min-width: 801px) and (prefers-reduced-motion: no-preference)');
 const image=document.querySelector<HTMLElement>('.quote-support');let frame=0;
 const update=()=>{frame=0;if(!image)return;if(!media.matches){image.style.removeProperty('--garden-drift');return}const box=image.getBoundingClientRect();if(box.top<innerHeight&&box.bottom>0){const progress=(innerHeight/2-(box.top+box.height/2))/(innerHeight+box.height);image.style.setProperty('--garden-drift',`${Math.max(-12,Math.min(12,progress*24))}px`)}};
 const scroll=()=>{if(!frame)frame=requestAnimationFrame(update)};scroll();window.addEventListener('scroll',scroll,{passive:true});media.addEventListener('change',scroll);return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',scroll);media.removeEventListener('change',scroll)};
},[]);
useEffect(()=>{const update=()=>document.querySelector('header')?.classList.toggle('is-scrolled',window.scrollY>24);update();window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update)},[]);
useEffect(()=>{function close(e:KeyboardEvent){if(e.key==='Escape')setMenu(false)}window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
return <><a className="skip" href="#main">Skip to content</a><PreviewCountdown/><div className="preview-note">Garden care demo · Illustrative imagery · Reviews awaiting verification <a href="/launch-notes.html">Launch notes <ArrowUpRight size={13}/></a></div><header><div className="nav-wrap"><Brand/><nav aria-label="Main navigation" className={menu?'open':''}>{nav.map(([label,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}</nav><a className="header-phone" aria-label={"Call "+site.phone} href={site.phoneHref}><Phone size={16}/><span>{site.phone}</span></a><a className="button header-quote" href="#quote">Request a Quote <ArrowUpRight size={17}/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></div></header>
<main id="main"><section id="home" className="hero cinematic-hero"><HeroVideo/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow"><Leaf size={16}/> GARDEN CARE · {site.area.toUpperCase()}</p><h1>Beautiful Gardens,<br/>Professionally<br className="desktop-break"/> Cared For</h1><p className="lead">Reliable garden maintenance, landscaping and arboriculture services across {site.areaSentence}.</p><div className="actions"><a className="button" href="#quote">Request a Quote <ArrowUpRight size={19}/></a><a className="button secondary" href="#work">View Our Work <ArrowRight size={18}/></a></div><p className="hero-local">Local <span>·</span> Reliable <span>·</span> Professional Garden Care</p></div><div className="hero-bottom"><span>{site.imageryNote}</span><a href="#services">Explore our services <ArrowRight size={15}/></a></div></section>
<div className="stats wrap reveal"><div><span className="stat-value">{site.rating}{site.rating!=='TBC'&&<span className="star">★</span>}</span><span>Local Rating</span></div><div><span className="stat-value">{site.reviewCount.replace("+","")}{site.reviewCount!=='TBC'&&<span className="plus">+</span>}</span><span>Customer Reviews</span></div><div><MapPin size={30} strokeWidth={1.5}/><span className="stat-area">{site.area}<small>Your local garden services</small></span></div></div>
<section className="section wrap" id="services"><div className="section-heading reveal"><div><p className="eyebrow">CARE FOR EVERY CORNER</p><h2>A little care. A garden you’ll love.</h2></div><p>From a regular mow to a thorough tidy-up, find the right care for your garden.</p></div><div className="service-grid">{services.map((s,i)=><article className="service-card botanical-anchor reveal" style={{transitionDelay:`${i%3*90}ms`}} key={s.title}>{i===0&&<BotanicalAccent/>}{i===2&&<BotanicalAccent opposite/>}<div className="service-top"><span className="round-icon"><s.icon size={27} strokeWidth={1.5}/></span><span className="number">0{i+1}</span></div><h3>{s.title}</h3><p>{s.copy}</p><a href="#quote" onClick={()=>setService(s.title)} aria-label={'Enquire about '+s.title}>Let’s talk about your garden <ArrowUpRight size={18}/></a></article>)}</div></section>
<section className="work-section section" id="work"><div className="wrap"><div className="section-heading reveal"><div><p className="eyebrow">THE DIFFERENCE IS IN THE DETAILS</p><h2>Our Work & Garden Inspiration</h2></div><div><p>Fresh lawns, tidy borders and outdoor spaces to enjoy.</p><p className="small-note">Illustrative demo images. Replace with verified business projects before launch.</p></div></div><div className="editorial-projects">{site.projects.map((project,i)=><article className="editorial-project" key={project.image}><div className="project-visual botanical-anchor reveal"><BotanicalAccent/>{i!==1&&<BotanicalAccent opposite/>}<button className="project-image" onClick={()=>setGallery(i)} aria-label={'View '+project.title}><img src={project.image} alt={project.alt} width={1200} height={900} loading="lazy"/></button></div><div className="project-info"><p className="eyebrow">0{i+1} / GARDEN CARE</p><h3>{project.title}</h3><p>{project.alt}.</p><button className="button secondary reveal" onClick={()=>setGallery(i)} aria-label={'View '+project.title}>View Project <ArrowUpRight size={18}/></button></div></article>)}</div><div className="work-bottom reveal"><p>Your garden could be next.</p><a className="text-link" href="#quote">Tell us what you have in mind <ArrowRight size={18}/></a></div></div></section>
<section className="section wrap" id="reviews"><div className="section-heading reveal"><div><p className="eyebrow">LOCAL CARE. LOCAL FEEDBACK.</p><h2>What Local Customers Say</h2></div><div className="rating"><div><strong>{site.rating}</strong>{site.rating!=='TBC'&&<span aria-label="five stars">★★★★★</span>}</div><p>{site.reviewCount} Customer Reviews</p></div></div><p className="review-template-note">{site.reviews.length ? "Verified customer feedback" : "Review template — genuine customer reviews to be added."}</p><div className="review-grid botanical-anchor"><BotanicalAccent/><BotanicalAccent opposite/>{(site.reviews.length?site.reviews:[null,null,null]).map((review,i)=><article className="review-card reveal" key={i}><Quote size={30} strokeWidth={1.2}/><p>{review?review.quote:<>Verified Google review<br/>to be inserted here.</>}</p><div className="review-person"><span>{String(i+1).padStart(2,'0')}</span><div>{review?review.name:"Verified customer name"}<small>{review?"Customer review":"To be supplied"}</small></div></div></article>)}</div></section>
<section className="area-section" id="areas"><div className="wrap area-inner reveal"><div><p className="eyebrow">ROOTED IN YOUR NEIGHBOURHOOD</p><h2>Local Garden Services in {site.area}</h2><p>Based around {site.areaSentence}, {site.name} provides garden maintenance, landscaping and arboriculture services across {site.coverage}. Tell us your postcode when you enquire and we’ll confirm availability for your area.</p><a className="text-link" href="#quote">Check your area <ArrowRight size={18}/></a></div><div className="area-panel botanical-anchor"><BotanicalAccent/><MapPin size={44} strokeWidth={1.2}/><h3>{site.area}</h3><div className="area-tags"><span>{site.coverage}</span></div><p>{site.address}</p></div></div></section>
<section className="section wrap quote-section" id="quote"><div className="quote-support reveal"><img src={site.supportingImage} alt="Illustrative residential garden with a lawn and planted borders in evening light" width={1200} height={900} loading="lazy"/><span>Space to unwind. A garden to enjoy.<small>Illustrative demo image</small></span></div><div className="quote-panel botanical-anchor reveal"><BotanicalAccent/><div className="quote-copy"><p className="eyebrow">LET’S TALK GARDENS</p><h2>Ready to Get Your Garden Sorted?</h2><p>Tell us what you need help with and we’ll make it easy to take the next step.</p><div className="call-card"><span className="round-icon"><Phone size={23}/></span><div><small>Prefer a chat?</small><a href={site.phoneHref}>Call {site.phone}</a></div></div><div className="form-disclaimer"><strong>Preview form</strong><p>Online enquiries aren’t connected yet. Please call to request a quote. Details entered here are not sent or saved.</p></div></div><form onSubmit={e=>{e.preventDefault();setNotice(service?'This is a preview — your enquiry has not been sent. Please call '+site.phone+' to request a quote.':'Please choose a service before continuing.')}}><div className="form-row"><label htmlFor="name">Your name<input id="name" name="name" autoComplete="name" placeholder="Full name" required maxLength={100}/></label><label htmlFor="phone">Phone number<input id="phone" name="phone" autoComplete="tel" type="tel" placeholder="Your contact number" required minLength={7} maxLength={20}/></label></div><div className="form-row"><label htmlFor="postcode">Postcode<input id="postcode" name="postcode" autoComplete="postal-code" placeholder="e.g. HP7 0NU" required maxLength={10}/></label><div className="field"><label htmlFor="service">Service required</label><Select value={service} onValueChange={setService} name="service" required><SelectTrigger id="service" className="service-select"><SelectValue placeholder="Choose a service"/></SelectTrigger><SelectContent position="popper">{services.map(s=><SelectItem value={s.title} key={s.title}>{s.title}</SelectItem>)}</SelectContent></Select></div></div><label htmlFor="message">Tell us about your garden<textarea id="message" name="message" placeholder="What would you like a hand with?" rows={4} required maxLength={2000}/></label><button className="button submit" type="submit">Request a Quote <ArrowUpRight size={19}/></button><p className="form-hint">Demo only · No enquiry is sent</p>{notice&&<p className="notice" role="status">{notice}</p>}</form></div></section></main>
<footer className="wrap"><div className="footer-main"><div><Brand/><p>Garden care across {site.area}.<br/>{site.address}</p><a className="footer-phone" href={site.phoneHref}>{site.phone}</a></div><div className="footer-links"><h3>Explore</h3>{nav.map(([name,id])=><a href={'#'+id} key={id}>{name}</a>)}</div><div className="footer-links"><h3>Garden care</h3>{services.map(s=><a key={s.title} href="#quote" onClick={()=>setService(s.title)}>{s.title}</a>)}</div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {site.name}</span><a href="/launch-notes.html">Preview launch notes <ArrowUpRight size={14}/></a></div></footer><div className="mobile-bar"><a className="button secondary" href={site.phoneHref}><Phone size={17}/> Call</a><a className="button" href="#quote">Request a Quote <ArrowUpRight size={17}/></a></div>
<Dialog open={gallery!==null} onOpenChange={open=>{if(!open)setGallery(null)}}><DialogContent className="gallery-dialog"><DialogTitle>{site.projects[gallery??0].title}</DialogTitle><DialogDescription>{site.imageryNote}</DialogDescription><img className="lightbox-image" src={site.projects[gallery??0].image} alt={site.projects[gallery??0].alt}/><div className="dialog-actions"><button className="button secondary" onClick={()=>setGallery(((gallery??0)+site.projects.length-1)%site.projects.length)}>Previous</button><span>{(gallery??0)+1} / {site.projects.length}</span><button className="button" onClick={()=>setGallery(((gallery??0)+1)%site.projects.length)}>Next <ArrowRight size={16}/></button></div></DialogContent></Dialog></>}
